apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer #NodePort
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 21000
    targetPort: 21000
    #nodePort: 21000
    name: ftps-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-deployment
        image: alpine_ftps
        imagePullPolicy: IfNotPresent
        #  env:
        #- name: USER
        #value: admin
        #- name: PASSWORD
        #value: password
